[build]
  publish = "dist"
  command = "gridsome build"
  functions = "functions"


[[headers]]
    for = "/*.css"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"
[[headers]]
    for = "/*.js"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"
[[headers]]
    for = "/*.svg"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"
[[headers]]
    for = "/*.png"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"
[[headers]]
    for = "/*.jpg"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"
[[headers]]
    for = "/*.gif"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"
[[headers]]
    for = "/*.ttf"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"
[[headers]]
    for = "/*.otf"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"
[[headers]]
    for = "/*.woff"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"
[[headers]]
    for = "/*.woff2"
    [headers.values]
        Cache-Control = "public, s-max-age=2592000"